spring:
  application:
    name: assignment

  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      format_sql: true
    defer-datasource-initialization: true   # 데이터 소스 초기화 시점 지연, SQL 실행 후 JPA 엔티티 데이터베이스 스키마에 맵핑

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    # 쿼리 파라미터
    org.hibernate.type: trace

jwt:
  secret: 718ac9bb28d97e6d8954a83ba244a7add8a737835724ad425d4033c1ff6dd7292688d577b4899516e49cf6fc8eaab87ba34944b71a03e06753215ab62c58f069

  access:
    expiration: 20000
    header: Authorization

  refresh:
    expiration: 90
    header: Authorization-refresh